# Generated by Django 3.2.16 on 2022-10-04 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221004_1124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='promo_id',
            new_name='promo',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='role_id',
            new_name='role',
        ),
    ]
